name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux-x86_64:
    name: Build for Linux (x86_64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkg-config libyaml-cpp-dev

      - name: Clone and Install FTXUI
        run: |
          git clone https://github.com/ArthurSonzogni/FTXUI.git /tmp/FTXUI
          cd /tmp/FTXUI
          mkdir build && cd build
          cmake ..
          sudo make install

      - name: Configure and Build Project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dashboard-linux-x86_64
          path: build/dashboard

  build-macos:
    name: Build for macOS (${{ matrix.arch }})
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x86_64, arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: brew install yaml-cpp pkg-config

      - name: Clone and Install FTXUI
        run: |
          git clone https://github.com/ArthurSonzogni/FTXUI.git /tmp/FTXUI
          cd /tmp/FTXUI
          mkdir build && cd build
          cmake .. -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }}
          sudo make install

      - name: Configure and Build Project
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }}
          make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dashboard-macos-${{ matrix.arch }}
          path: build/dashboard

  build-linux-arm64:
    name: Build for Linux (ARM64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build for arm64 via emulation
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: arm64
          distro: ubuntu22.04
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          run: |
            # 1. Install dependencies inside the ARM container
            apt-get update
            apt-get install -y build-essential cmake pkg-config libyaml-cpp-dev git

            # 2. Build and install FTXUI for ARM
            git clone https://github.com/ArthurSonzogni/FTXUI.git /tmp/FTXUI
            cd /tmp/FTXUI
            mkdir build && cd build
            cmake ..
            make install

            # 3. Build the project inside the ARM container
            cd /github/workspace
            mkdir build
            cd build
            cmake ..
            make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dashboard-linux-arm64
          path: build/dashboard