name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13]  # Linux x64, macOS ARM, macOS Intel

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkg-config libyaml-cpp-dev
        else
          brew update
          brew install cmake pkg-config yaml-cpp
        fi

    - name: Clone and Install FTXUI
      run: |
        git clone https://github.com/ArthurSonzogni/FTXUI.git /tmp/FTXUI
        cd /tmp/FTXUI
        mkdir build && cd build
        cmake ..
        sudo make install || make install

    - name: Configure and Build Project
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dashboard-${{ matrix.os }}
        path: build/dashboard